Legg til om barnet er sammen med deg i ppsb søknad
navikt/k9-brukerdialog-prosessering pull request #173
Opened 2024-06-20 13:28 UTC by selbekk

Samme som forrige PR, men med dev- i tittelen, så den kan deployes til Q

2024-06-20 13:39 UTC, ramrock93 approved these changes

2024-06-21 09:33 UTC, frodehansen2 requested changes
Noen kommentarer

2024-06-21 09:33 UTC, frodehansen2 commented on src/main/resources/handlebars/pleiepenger-sykt-barn-soknad.hbs
> +                                {{#isNotNull opphold.erSammenMedBarnet }}
Her må rekkefølgen endres. Vi spør om en er sammen med barnet først; og kun dersom det er tilfelle, spør vi om barnet er innlagt.

2024-06-21 09:33 UTC, frodehansen2 commented on src/main/resources/handlebars/pleiepenger-sykt-barn-soknad.hbs
>                          {{#if opphold.erUtenforEØS}}
Vi spør også om barnet er sammen med deg om det er innenfor EØS

2024-06-21 09:38 UTC, selbekk commented on src/main/resources/handlebars/pleiepenger-sykt-barn-soknad.hbs
>                          {{#if opphold.erUtenforEØS}}
Alright!

2024-06-25 07:30 UTC, merged